---
name: Build & push image to registry

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      registry:
        required: true
        type: string
      context:
        required: false
        default: './'
        type: string
      dockerfile:
        required: false
        default: './Dockerfile'
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    name: Build & push image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker-Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Fetch Docker meta data
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ inputs.registry }}/${{ inputs.image_name }}
          flavor: |
            latest=true
          tags: |
            type=sha,format=short,prefix=,priority=100
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Echo image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
